"""add new column keyword matches

Revision ID: 14f155107835
Revises: a0d41ab32b0d
Create Date: 2018-03-19 11:55:24.281385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f155107835'
down_revision = 'a0d41ab32b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('keywordMatches', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_document_keywordMatches'), 'document', ['keywordMatches'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_keywordMatches'), table_name='document')
    op.drop_column('document', 'keywordMatches')
    # ### end Alembic commands ###
