"""add new column keyword matches

Revision ID: 23c48bb6aa5b
Revises: 14f155107835
Create Date: 2018-03-19 12:10:33.604117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c48bb6aa5b'
down_revision = '14f155107835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_keywordMatches'), 'document', ['keywordMatches'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_keywordMatches'), table_name='document')
    # ### end Alembic commands ###
