"""empty message

Revision ID: bfe871a23b54
Revises: cf372f2f534b
Create Date: 2018-03-29 16:52:55.628653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe871a23b54'
down_revision = 'cf372f2f534b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('sentiment', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_document_sentiment'), 'document', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_sentiment'), table_name='document')
    op.drop_column('document', 'sentiment')
    # ### end Alembic commands ###
