"""empty message

Revision ID: c59cdccb8d68
Revises: 62e6d393668e
Create Date: 2018-03-30 15:40:29.752029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59cdccb8d68'
down_revision = '62e6d393668e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw__text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('raw_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_text',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('raw__text')
    # ### end Alembic commands ###
