"""adkeyword not unique

Revision ID: cf372f2f534b
Revises: 0070b69fc1bc
Create Date: 2018-03-19 12:59:54.406711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf372f2f534b'
down_revision = '0070b69fc1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txtLocation', sa.String(length=300), nullable=True),
    sa.Column('imgLocation', sa.String(length=300), nullable=True),
    sa.Column('keywordMatches', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_imgLocation'), 'document', ['imgLocation'], unique=True)
    op.create_index(op.f('ix_document_keywordMatches'), 'document', ['keywordMatches'], unique=False)
    op.create_index(op.f('ix_document_txtLocation'), 'document', ['txtLocation'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_txtLocation'), table_name='document')
    op.drop_index(op.f('ix_document_keywordMatches'), table_name='document')
    op.drop_index(op.f('ix_document_imgLocation'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
